### ISSUE TITLE
Roadmap for stiffness detection and automatic switching algorithms

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiffEq/OrdinaryDiffEq.jl#288]
Here is a roadmap that I propose for the stiffness detection and automatic switching algorithms project.

## The skeleton (`DP5`, `Tsit5` ⟷ `Rodas5`)

- [x] Make necessary changes to the integrator type #275 
- [x] The largest eigenvalue estimation in explicit RK algorithms (`DP5`, `Tsit5`) #275
- [x] The largest eigenvalue estimation in the implicit algorithm #282 
   - Maybe scale the max norm of the Jacobian matrix accordingly to match the estimation from explicit RKs?
- [x] Basic switching strategies #287 #289 
- [ ] Use benchmark results to optimize the strategies
