### ISSUE TITLE
Finalizing the Jacobian saga

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#952]
To end this saga of the Jacobian reuse changes which really came into fruition with https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/927, we will want to do the following:

- [ ] OOP Wfact
- [ ] Skip calculating W even in the Wfact case if not necessary (becuase Wfact could still be expensive) 
- [ ] Add a test for the DiffEqGPU case
- [ ] Test https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/914 is factorizing once
- [ ] Test https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/778
- [ ] Test https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/262 ? Might already be complete
- [ ] Change StochasticDiffEq to match
- [ ] More clearly identify Rosenbrock and FIRK in the implementation
- [ ] Improved Jacobian reuse: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/871

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/521 might be involved as well.

**Comment by kanav99** [comment]
I would like to add the changes for DAEs in the list too, just so that one is tracked too. I am out of sync these days and this list can help
